### ISSUE TITLE
Composer Update issue on Windows

### ISSUE THREAD

**Issue by hiamitchaurasia** [imelgrat/freegoip#1]
I get this error when I try to install it.

D:\Dev\UniServerZ\www>php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package imelgrat/freegoip \* is satisfiable by imelgrat/freegoip[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by imelgrat** [comment]
Hi! I'm still working on a proper release so, in order to make the package work, you'll need to lower your minimum stability requirements to "dev".

**Comment by imelgrat** [comment]
Hello,
I published a stable release. You can now work using the usual "require" and "require-dev" syntax.
